name: smartstall_operator
description: "SmartStall Operator – Automated Cleaning Robot Controller"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  dio: ^5.4.0
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  camera: ^0.11.0+2
  opencv_dart: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#67E279"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/animations/
    - assets/lottie/
    - assets/images/
    - assets/fonts/
